[package]
name        = "areas"
description = "A simple program"
version     = "0.1.0"
repository  = "github:michelou/flix-examples"
flix        = "0.65.0"
license     = "Apache-2.0"
authors     = []

[dependencies]
# e.g. "github:flix/museum-clerk" = "1.1.0"

[mvn-dependencies]
# e.g. "org.postgresql:postgresql" = "1.2.3.4"

[jar-dependencies]
# e.g. "junit.jar" = "url:https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.9.3/junit-jupiter-api-5.9.3.jar"
